# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Under Maintenance'), ('BREAKDOWN', 'Breakdown'), ('RETIRED', 'Retired')], db_index=True, default='AVAILABLE', max_length=16)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('maintenance_due', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal charging rate for budget vs actuals.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ('asset_code',),
            },
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('DEPLOY', 'Deployed to Site'), ('RETURN', 'Returned to Yard'), ('TRANSFER', 'Transferred Between Sites'), ('MAINTENANCE', 'Sent for Maintenance'), ('BREAKDOWN', 'Reported Breakdown'), ('REPAIR', 'Repair Completed')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipment Log',
                'verbose_name_plural': 'Equipment Logs',
                'ordering': ('-occurred_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_sku', models.CharField(help_text='SKU from the POS catalogue (Repo #1).', max_length=64)),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='pc', max_length=32)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('CONSUMED', 'Consumed')], default='GOOD', max_length=16)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Stock',
                'verbose_name_plural': 'Site Stock',
                'ordering': ('site', 'item_name'),
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('quantity_total', models.PositiveIntegerField(default=1)),
                ('quantity_available', models.PositiveIntegerField(default=1)),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('CONSUMED', 'Consumed')], default='GOOD', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ('site', 'name'),
            },
        ),
    ]
