# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_projects', '0002_initial'),
        ('apps_site_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_equipment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Current site assignment (null when in the yard).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='apps_projects.site'),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='apps_site_inventory.equipment'),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentlog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_logs', to='apps_projects.site'),
        ),
        migrations.AddField(
            model_name='sitestock',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='apps_projects.site'),
        ),
        migrations.AddField(
            model_name='tool',
            name='custodian',
            field=models.ForeignKey(blank=True, help_text='Person accountable for these tools on site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custodian_tools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tool',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='apps_projects.site'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['status', 'site'], name='apps_site_i_status_87c5db_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitestock',
            constraint=models.UniqueConstraint(fields=('site', 'item_sku'), name='unique_sku_per_site'),
        ),
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.UniqueConstraint(fields=('site', 'code'), name='unique_tool_code_per_site'),
        ),
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__lte', models.F('quantity_total'))), name='tool_available_lte_total'),
        ),
    ]
