# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Assigned Project Manager.', limit_choices_to={'role': 'PROJECT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='apps_projects.project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='apps_projects.project'),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='apps_projects.project'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='apps_projects.projectphase'),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='apps_projects.site'),
        ),
        migrations.AddConstraint(
            model_name='projectphase',
            constraint=models.UniqueConstraint(fields=('project', 'sequence'), name='unique_phase_sequence_per_project'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'due_date'], name='apps_projec_project_78e505_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'site'], name='apps_projec_status_0346fc_idx'),
        ),
    ]
