# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=64, unique=True)),
                ('debtor_name', models.CharField(max_length=255)),
                ('debtor_contact', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cached sum of recorded payments; call recompute() after changes.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WRITTEN_OFF', 'Written Off')], db_index=True, default='OPEN', max_length=16)),
                ('pos_collectible_ref', models.CharField(blank=True, help_text='Matching collectible reference in the POS ledger.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collectible',
                'verbose_name_plural': 'Collectibles (Utang)',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CollectiblePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CHECK', 'Check'), ('GCASH', 'E-Wallet'), ('MATERIAL_OFFSET', 'Material Offset')], default='CASH', max_length=16)),
                ('reference_no', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Collectible Payment',
                'verbose_name_plural': 'Collectible Payments',
                'ordering': ('-paid_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ExpenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIALS', 'Materials'), ('LABOR', 'Labor'), ('EQUIPMENT', 'Equipment & Rental'), ('SUBCONTRACTOR', 'Subcontractor'), ('OVERHEAD', 'Overhead & Admin'), ('OTHER', 'Other')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('incurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt_no', models.CharField(blank=True, max_length=64)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Log',
                'verbose_name_plural': 'Expense Logs',
                'ordering': ('-incurred_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MATERIALS', 'Materials'), ('LABOR', 'Labor'), ('EQUIPMENT', 'Equipment & Rental'), ('SUBCONTRACTOR', 'Subcontractor'), ('OVERHEAD', 'Overhead & Admin'), ('OTHER', 'Other')], max_length=16)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Budget',
                'verbose_name_plural': 'Project Budgets',
                'ordering': ('project', 'category'),
            },
        ),
    ]
