# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_financials', '0001_initial'),
        ('apps_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectibles', to='apps_projects.project'),
        ),
    ]
