# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_financials', '0002_initial'),
        ('apps_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_collectibles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectiblepayment',
            name='collectible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apps_financials.collectible'),
        ),
        migrations.AddField(
            model_name='collectiblepayment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='apps_projects.project'),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='apps_projects.project'),
        ),
        migrations.AddField(
            model_name='expenselog',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='apps_financials.projectbudget'),
        ),
        migrations.AddIndex(
            model_name='collectible',
            index=models.Index(fields=['status', 'due_date'], name='apps_financ_status_ba44aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectbudget',
            constraint=models.UniqueConstraint(fields=('project', 'category'), name='unique_budget_category_per_project'),
        ),
        migrations.AddIndex(
            model_name='expenselog',
            index=models.Index(fields=['project', 'category'], name='apps_financ_project_82c676_idx'),
        ),
        migrations.AddIndex(
            model_name='expenselog',
            index=models.Index(fields=['status', 'incurred_on'], name='apps_financ_status_10c2c3_idx'),
        ),
    ]
