# Generated by Django 5.2.17 on 2026-09-23 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_projects', '0002_initial'),
        ('apps_requisitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_material_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='apps_projects.site'),
        ),
        migrations.AddField(
            model_name='materialrequestitem',
            name='material_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apps_requisitions.materialrequest'),
        ),
        migrations.AddField(
            model_name='possynclog',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sync_logs', to='apps_requisitions.materialrequest'),
        ),
        migrations.AddField(
            model_name='releasetoken',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_release_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releasetoken',
            name='material_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_tokens', to='apps_requisitions.materialrequest'),
        ),
        migrations.AddField(
            model_name='possynclog',
            name='release_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sync_logs', to='apps_requisitions.releasetoken'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['status', 'priority'], name='apps_requis_status_9c34e9_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['project', 'status'], name='apps_requis_project_b75eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='releasetoken',
            index=models.Index(fields=['status', 'expires_at'], name='apps_requis_status_e66f9c_idx'),
        ),
        migrations.AddIndex(
            model_name='possynclog',
            index=models.Index(fields=['success', 'created_at'], name='apps_requis_success_5c6f80_idx'),
        ),
    ]
